### ISSUE TITLE
兄弟我试了下还是不行

### ISSUE THREAD

**Issue by doudoumao1031** [wlx200510/react-wlx#1]
$ npm install --force
npm WARN using --force I sure hope you know what you are doing.

> fsevents@1.1.2 install C:\Users\dou\Desktop\exercise\reactDemos\react-wlx\node_modules\fsevents
> node install

> node-sass@4.7.2 install C:\Users\dou\Desktop\exercise\reactDemos\react-wlx\node_modules\node-sass
> node scripts/install.js

module.js:538
    throw err;
    ^

Error: Cannot find module 'generate-function'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\dou\Desktop\exercise\reactDemos\react-wlx\node_modules\is-my-json-valid\index.js:2:14)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

用npm install --force 装了两次都报错

**Comment by doudoumao1031** [comment]
$ cnpm i --force
platform unsupported babel-loader@7.1.2 › webpack@3.8.1 › watchpack@1.4.0 › chokidar@1.7.0 › fsevents@^1.0.0 Package require os(darwin) not compatible with your platform(win32)
[fsevents@^1.0.0] optional install error: Package require os(darwin) not compatible with your platform(win32)
platform unsupported fsevents@1.1.2 Package require os(darwin) not compatible with your platform(win32)
× Install fail! UnSupportedPlatformError: Package require os(darwin) not compatible with your platform(win32)
UnSupportedPlatformError: Package require os(darwin) not compatible with your platform(win32)
    at _install (C:\Users\dou\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\install.js:197:19)
    at _install.next (<anonymous>)
    at onFulfilled (C:\Users\dou\AppData\Roaming\npm\node_modules\cnpm\node_modules\co\index.js:65:19)
    at <anonymous>
npminstall version: 3.2.1
npminstall args: C:\Program Files\nodejs\node.exe C:\Users\dou\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\bin\install.js --china --userconfig=C:\Users\dou\.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=http://registry.npm.taobao.org --force

然后又用 cnpm i --force试了下 报的是IOS依赖包那个错误
兄弟你帮我看看 感激不尽

**Comment by wlx200510** [comment]
用npm呢？



发自我的小米手机
在 liang <notifications@github.com>，2018年2月11日 21:24写道：

$ cnpm i --force
platform unsupported babel-loader@7.1.2 › webpack@3.8.1 › watchpack@1.4.0 › chokidar@1.7.0 › fsevents@^1.0.0 Package require os(darwin) not compatible with your platform(win32)
[fsevents@^1.0.0] optional install error: Package require os(darwin) not compatible with your platform(win32)
platform unsupported fsevents@1.1.2 Package require os(darwin) not compatible with your platform(win32)
× Install fail! UnSupportedPlatformError: Package require os(darwin) not compatible with your platform(win32)
UnSupportedPlatformError: Package require os(darwin) not compatible with your platform(win32)
at _install (C:\Users\dou\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\install.js:197:19)
at _install.next ()
at onFulfilled (C:\Users\dou\AppData\Roaming\npm\node_modules\cnpm\node_modules\co\index.js:65:19)
at
npminstall version: 3.2.1
npminstall args: C:\Program Files\nodejs\node.exe C:\Users\dou\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\bin\install.js --china --userconfig=C:\Users\dou.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=http://registry.npm.taobao.org --force

然后又用 cnpm i --force试了下 报的是IOS依赖包那个错误
兄弟你帮我看看 感激不尽

**Comment by wlx200510** [comment]
额……你这个是node版本的问题吧……用最新版也是？



发自我的小米手机
在 liang <notifications@github.com>，2018年2月11日 21:23写道：

$ npm install --force
npm WARN using --force I sure hope you know what you are doing.

fsevents@1.1.2 install C:\Users\dou\Desktop\exercise\reactDemos\react-wlx\node_modules\fsevents
node install

node-sass@4.7.2 install C:\Users\dou\Desktop\exercise\reactDemos\react-wlx\node_modules\node-sass
node scripts/install.js

module.js:538
throw err;
^

Error: Cannot find module 'generate-function'
at Function.Module._resolveFilename (module.js:536:15)
at Function.Module._load (module.js:466:25)
at Module.require (module.js:579:17)
at require (internal/module.js:11:18)
at Object. (C:\Users\dou\Desktop\exercise\reactDemos\react-wlx\node_modules\is-my-json-valid\index.js:2:14)
at Module._compile (module.js:635:30)
at Object.Module._extensions..js (module.js:646:10)
at Module.load (module.js:554:32)
at tryModuleLoad (module.js:497:12)
at Function.Module._load (module.js:489:3)

用npm install --force 装了两次都报错

**Comment by wlx200510** [comment]
这个需要研究下node-sass的安装



发自我的小米手机
在 liang <notifications@github.com>，2018年2月11日 21:23写道：

$ npm install --force
npm WARN using --force I sure hope you know what you are doing.

fsevents@1.1.2 install C:\Users\dou\Desktop\exercise\reactDemos\react-wlx\node_modules\fsevents
node install

node-sass@4.7.2 install C:\Users\dou\Desktop\exercise\reactDemos\react-wlx\node_modules\node-sass
node scripts/install.js

module.js:538
throw err;
^

Error: Cannot find module 'generate-function'
at Function.Module._resolveFilename (module.js:536:15)
at Function.Module._load (module.js:466:25)
at Module.require (module.js:579:17)
at require (internal/module.js:11:18)
at Object. (C:\Users\dou\Desktop\exercise\reactDemos\react-wlx\node_modules\is-my-json-valid\index.js:2:14)
at Module._compile (module.js:635:30)
at Object.Module._extensions..js (module.js:646:10)
at Module.load (module.js:554:32)
at tryModuleLoad (module.js:497:12)
at Function.Module._load (module.js:489:3)

用npm install --force 装了两次都报错

**Comment by doudoumao1031** [comment]
跑通了
先用npm i --force安装了次
然后再用cnpm 单独安装的node-sass和node-gyp
就成了 谢了兄弟
有缘分加我Q 549580311 
不打不相识O(∩_∩)O哈哈~

**Comment by 15826954460** [comment]
我想问问兄台，为啥一定要用 npm i --force啊, 都不知道干啥的
但是还是报错
\ [30/56] Installing fsevents@1.1.2platform unsupported fsevents@1.1.2 Package require os(darwin) not compatible with your platform(win32)
× **Install fail! UnSupportedPlatformError: Package require os(darwin) not compatible with your platform(win32)
UnSupportedPlatformError: Package require os(darwin) not compatible with your platform(win32)
    at _install (C:\Users\baiyunsong\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\install.js:197:19)
    at next (native)
    at onFulfilled** (C:\Users\baiyunsong\AppData\Roaming\npm\node_modules\cnpm\node_modules\co\index.js:65:19)

**Comment by wlx200510** [comment]
额  这是因为fsevent对安装环境是硬要求  你用的是win10吗？



发自我的小米手机
在 Aram <notifications@github.com>，2018年3月5日 下午10:32写道：

我想问问兄台，为啥一定要用 npm i --force啊, 都不知道干啥的
但是还是报错
\ [30/56] Installing fsevents@1.1.2platform<mailto:fsevents@1.1.2platform> unsupported fsevents@1.1.2 Package require os(darwin) not compatible with your platform(win32)
× Install fail! UnSupportedPlatformError: Package require os(darwin) not compatible with your platform(win32)
UnSupportedPlatformError: Package require os(darwin) not compatible with your platform(win32)
at _install (C:\Users\baiyunsong\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\install.js:197:19)
at next (native)
at onFulfilled (C:\Users\baiyunsong\AppData\Roaming\npm\node_modules\cnpm\node_modules\co\index.js:65:19)
